### ISSUE TITLE
How to get more spells

### ISSUE THREAD

**Issue by cutemeilu** [KingArvis/Classes#6]
I'm using this on a survival server 
I'm a mage
How to get more spells?

**Comment by Robified0** [comment]
First, you'll want to follow your advancements. It gives you some instructions on how to get new spells. Basically, put a piece of lapis lazuli in the Magic Table with a Book & Quill. You'll get a message that you learned about it.

Then do the same with the different elemental essences (details are listed in the advancements).

Then try with random items like coal, ice, packed ice, nautilus shell, ender eye, etc (making sure to use a Book & Quill with it)
